http:
  routers:
    focuss-uptime-kuma-http:
      rule: Host(`status.focussdev.space`)
      entryPoints:
        - http
      middlewares:
        - redirect-to-https
      service: focuss-uptime-kuma
    focuss-uptime-kuma-https:
      rule: Host(`status.focussdev.space`)
      entryPoints:
        - https
      middlewares:
        - focuss-uptime-kuma-frame-policy
      service: focuss-uptime-kuma
      tls:
        certResolver: letsencrypt
  middlewares:
    focuss-uptime-kuma-frame-policy:
      headers:
        customResponseHeaders:
          Content-Security-Policy: "frame-ancestors https://app.focussdev.space"
  services:
    focuss-uptime-kuma:
      loadBalancer:
        servers:
          - url: http://focuss-uptime-kuma:3001
